### PR TITLE
Add support for shorewall params

### PR DESCRIPTION
**Pull request by spacedog**
Signed-off-by: Anton Baranov <abaranov@linuxfoundation.org>

### CODE REVIEW

**Comment by cedef** [comment]
Would be great to merge this feature into master !
Can't wait to use it :)

**Comment by inkblot** [comment]
This seems like a good candidate for `augeas` resources. Would you mind giving it a try?

**Comment by hex2a** [comment]
any change this will be merged?

**Comment by inkblot** [comment]
This change is included in version 5.0.2 of the module on the Puppet Forge. Thanks for the PR!

**Pull request merged**
