### PR TITLE
Fix rather embarassing issue in shorewall::simple

### PR DESCRIPTION
**Pull request by inkblot**
A couple of problems with the shorewall::port declaration at the bottom of the
class. First, no title for the resource. Second, there is a required parameter
that is not given a value.

Thanks to @Kreichi for sending the error! Closes issue #11

### CODE REVIEW

**Comment by inkblot** [comment]
@Kriechi, I've applied your suggested change and one additional change on this branch. Could you please try it out and let me know if you have any additional problems with `shorewall::simple`?

**Comment by inkblot** [comment]
Also, note that `shorewall::simple` is intended basically for workstations and will cut off incoming traffic other than ping. If you are applying this on a node to which you do not have console access, you can enable access via SSH using this additionally declaration in the node's manifest:

```
shorewall::simple::port { 'port-ssh':
    proto => 'tcp',
    port  => '22',
}
```

**Comment by Kriechi** [comment]
Shorewall already ships a macro for SSH (like for Ping and many other common things).

On second thought - shouldn't you be using `shorewall::simple::port` in `simple.pp`?

**Comment by inkblot** [comment]
So I did finally spin up a VM to try the `shorewall::simple` class on. It's had showstopper problems apparently all the way back to when I refactored for version 2.0.0 of the module. I've got a version now that works and I'm happy with.

The new default behavior is a little different. I have removed the need to declare any ports or interfaces in a node's manifest. These are handled inside the `shorewall::simple` class.

**Comment by inkblot** [comment]
This PR is included in version 4.4.0 of the module published on the Puppet Forge.

**Pull request merged**
