### PR TITLE
Add initial documentation

### PR DESCRIPTION
**Pull request by sts**
Adding a Readme.

### CODE REVIEW

**Comment by inkblot** [comment]
It's a good start. Thanks for the effort so far! Should I consider this a work in progress?

**Comment by sts** [comment]
Haven't had time to look into this again yet.

**Comment by raoulbhatia** [comment]
Can we merge so that others can build on this?

**Comment by sts** [comment]
Yes please just merge it. :-)

**Comment by inkblot** [comment]
This change is included in version 5.1.0 of the module on the Puppet Forge.

**Pull request merged**
